### ISSUE TITLE
a few small issues

### ISSUE THREAD

**Issue by matthewjacobson** [ArtBlocks/artblocks-engine-react#1]
Hello! I ran into a few small issues when setting up this front end with the plottables contract.

1) [Here](https://github.com/ArtBlocks/artblocks-engine-react/blob/bdd86f0cfa37a7125293be556e7c0c4cda841565/src/components/ProjectList.tsx#L30) `data.projects` was sorted in the opposite direction than was coded for so the pagination wasn't working correctly. My simple fix: `const { projectId } = data.projects[0];`

2) I was having an issue with the [useProject](https://github.com/ArtBlocks/artblocks-engine-react/blob/master/src/hooks/useProject.ts) subgraph query. Upon further investigation the contract address that the subgraph was expecting is all lowercase. Not sure if this would be an issue for other PBAB contracts but just wanted to add a note here. It was easily fixed by just changing the REACT_APP_CORE_CONTRACT_ADDRESS .env variable to match what was expected by the subgraph.

3) [Here](https://github.com/ArtBlocks/artblocks-engine-react/blob/bdd86f0cfa37a7125293be556e7c0c4cda841565/src/components/TokenPreview.tsx#L39) I believe the contract address is expected to be in the REACT_APP_GENERATOR_URL .env variable directly. This matches up with [this line](https://github.com/ArtBlocks/artblocks-engine-react/blob/bdd86f0cfa37a7125293be556e7c0c4cda841565/src/components/TokenPreview.tsx#L75) as well. This was causing all of the live links and iframes to be broken. Easy fix: `src={`${generatorUrl}/${tokenId}`}` or change line 75 to match 39.

That is all I have found so far. Haven't had a chance to test out minting functionality yet though. Happy to put this in a PR - just let me know.

Anyway thanks so much for putting this together!

**Comment by rubentd** [comment]
Thanks for reporting this @matthewjacobson  👍 I'll take care of it

**Comment by jakerockland** [comment]
TYVM @rubentd 💜 💜 💜
